export const ONCHANGE_THEME = "ONCHANGE_THEME";
export const ONCHANGE_COLOR = "ONCHANGE_COLOR";
export const ONCHANGE_ACTIVE_PRESET = "ONCHANGE_ACTIVE_PRESET";
export const ONCHANGE_PRESETS = "ONCHANGE_PRESETS";
export const SET_THEME = "SET_THEME";
